//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigValidation.ConfigErrors", typeof(ConfigErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string CV001 {
            get {
                return ResourceManager.GetString("CV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json is invalid.
        /// </summary>
        internal static string CV002 {
            get {
                return ResourceManager.GetString("CV002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema did not validate.
        /// </summary>
        internal static string CV003 {
            get {
                return ResourceManager.GetString("CV003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $/location must be washington.
        /// </summary>
        internal static string CV004 {
            get {
                return ResourceManager.GetString("CV004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $/name.first value length less than 5.
        /// </summary>
        internal static string CV005 {
            get {
                return ResourceManager.GetString("CV005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $/name.last value length less than 5.
        /// </summary>
        internal static string CV006 {
            get {
                return ResourceManager.GetString("CV006", resourceCulture);
            }
        }
    }
}
